name = "vibebase-core"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Workers Assets for dashboard
assets = { directory = "../dashboard/dist", binding = "ASSETS", run_worker_first = true }

# Enable Workers Logs
[observability]
enabled = true

# D1 Database binding (will be auto-configured during setup)
[[d1_databases]]
binding = "DB"
database_name = "vibebase-db"
database_id = "REPLACE_WITH_ACTUAL_DATABASE_ID"

# R2 Storage bindings
[[r2_buckets]]
binding = "SYSTEM_STORAGE"
bucket_name = "vibebase-system"

[[r2_buckets]]
binding = "USER_STORAGE"
bucket_name = "vibebase-storage"

# KV Namespace for sessions (will be auto-configured during setup)
[[kv_namespaces]]
binding = "SESSIONS"
id = "REPLACE_WITH_ACTUAL_KV_ID"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }