name = "vibebase"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Workers Assets disabled - handle all routing in Worker
# assets = { directory = "../dashboard/dist" }

# Enable Workers Logs
[observability]
enabled = true

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "vibebase-db"
database_id = "577a108b-06c4-4d50-ab3c-dcc39d3926e5"


# R2 Storage bindings
[[r2_buckets]]
binding = "SYSTEM_STORAGE"
bucket_name = "vibebase-system"

[[r2_buckets]]
binding = "USER_STORAGE"
bucket_name = "vibebase-storage"

# KV Namespace for sessions (will be auto-configured during setup)
[[kv_namespaces]]
binding = "SESSIONS"
id = "63a32a4e4bdf4699a1447d7f5e56c74f"

[vars]
ENVIRONMENT = "production"
VIBEBASE_AUTH_URL = "https://auth.vibebase.workers.dev"
DEPLOYMENT_DOMAIN = "vibebase.mesongo.workers.dev"
WORKER_NAME = "vibebase"

[env.development.vars]
ENVIRONMENT = "development"
VIBEBASE_AUTH_URL = "https://auth.vibebase.workers.dev"
DEPLOYMENT_DOMAIN = "localhost:8787"
WORKER_NAME = "vibebase-dev"