name = "viveforge-core"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Workers Assets for dashboard
assets = { directory = "../dashboard/dist" }

# Enable Workers Logs
[observability]
enabled = true

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "viveforge-db"
database_id = "e8855c8b-a012-4609-8680-25dd03646254"

# R2 Storage binding (will be created later)
# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "viveforge-storage"

# KV Namespace for sessions (will be created on first deploy)
# [[kv_namespaces]]
# binding = "SESSIONS"
# id = "YOUR_KV_NAMESPACE_ID"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }