name = "viveforge"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Workers Assets for dashboard
assets = { directory = "../dashboard/dist" }

# Enable Workers Logs
[observability]
enabled = true

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "viveforge-db"
database_id = "889a7128-6ea0-4ac2-a838-b2f07299e9ba"

# R2 Storage bindings
[[r2_buckets]]
binding = "SYSTEM_STORAGE"
bucket_name = "viveforge-system"

[[r2_buckets]]
binding = "USER_STORAGE"
bucket_name = "viveforge-storage"

# KV Namespace for sessions (will be auto-configured during setup)
[[kv_namespaces]]
binding = "SESSIONS"
id = "63a32a4e4bdf4699a1447d7f5e56c74f"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }